# Generated by Django 4.2.16 on 2024-10-01 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(blank=True, max_length=255, null=True)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=250, null=True)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_frame', models.CharField(blank=True, max_length=15, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=90, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=10)),
                ('order_no', models.CharField(max_length=55)),
                ('api_name', models.CharField(max_length=55)),
                ('currency', models.CharField(max_length=10)),
                ('order_1', models.CharField(blank=True, max_length=255, null=True)),
                ('order_2', models.CharField(blank=True, max_length=255, null=True)),
                ('order_3', models.CharField(blank=True, max_length=255, null=True)),
                ('order_4', models.CharField(blank=True, max_length=255, null=True)),
                ('order_5', models.CharField(blank=True, max_length=255, null=True)),
                ('order_6', models.CharField(blank=True, max_length=255, null=True)),
                ('order_7', models.CharField(blank=True, max_length=255, null=True)),
                ('order_8', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('time_frame', models.CharField(max_length=20)),
                ('strategy', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('entry', models.BooleanField(default=False)),
                ('exit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=255)),
                ('broker', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('strategy', models.CharField(blank=True, max_length=255, null=True)),
                ('time_frame', models.CharField(max_length=50)),
                ('long_or_short', models.CharField(max_length=255)),
                ('stop_loss', models.CharField(max_length=255)),
                ('risk_value', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=255)),
                ('broker', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('strategy', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.CharField(max_length=50)),
                ('local_currency', models.CharField(max_length=255)),
                ('time_frame', models.CharField(max_length=50)),
                ('long_or_short', models.CharField(max_length=255)),
                ('stop_loss', models.CharField(max_length=255)),
                ('risk_value', models.CharField(max_length=255)),
                ('automation', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255)),
                ('broker', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('api_type', models.CharField(choices=[('forex', 'Forex API'), ('crypto', 'Crypto API'), ('stock', 'Stock API')], max_length=50)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
