# Generated by Django 5.1.1 on 2024-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_openorders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='openorders',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
