# Generated by Django 5.1.1 on 2024-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_openorders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='option_strategies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
