# Generated by Django 5.1.1 on 2024-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_orders_option_strategies_orders_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategydata',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
