# Generated by Django 5.1.1 on 2024-10-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_strategydata_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.apiintegration'),
        ),
    ]
