# Generated by Django 5.1.1 on 2024-10-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_orders_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='openorders',
            name='option_strategies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openorders',
            name='order_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
