# Generated by Django 5.1.1 on 2024-10-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_openorders_option_strategies_openorders_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openorders',
            name='broker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='broker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
