# Generated by Django 5.1.1 on 2024-10-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_openorders_broker_alter_orders_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='openorders',
            name='ord_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
