# Generated by Django 5.1.1 on 2024-10-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_openorders_ord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategydata',
            name='api_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='strategydata',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='strategydata',
            name='pl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
