# Generated by Django 5.1.1 on 2024-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmodule', '0002_alter_modellog_instance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance'), ('Custom', 'Custom Plan')], default='Basic', max_length=20)),
                ('billings', models.BooleanField(default=False)),
                ('unlimited_strategy_data', models.BooleanField(default=False)),
                ('unlimited_orders', models.BooleanField(default=False)),
                ('api_keys', models.IntegerField(default=0)),
                ('ai_assistant', models.BooleanField(default=False)),
                ('unlimited_devices', models.BooleanField(default=False)),
                ('supports_long', models.BooleanField(default=False)),
                ('supports_short', models.BooleanField(default=False)),
                ('all_markets', models.BooleanField(default=False)),
                ('all_brokers', models.BooleanField(default=False)),
                ('custom_strategy', models.BooleanField(default=False)),
                ('dedicated_support_manager', models.BooleanField(default=False)),
            ],
        ),
    ]
