# Generated by Django 5.1.1 on 2024-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmodule', '0004_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
