# Generated by Django 5.1.1 on 2024-10-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmodule', '0007_usertransections'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractiveplan',
            name='transactions_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertransections',
            name='transactions_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
