# Generated by Django 5.1.1 on 2024-10-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authmodule', '0008_useractiveplan_transactions_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractiveplan',
            old_name='start_data',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='usertransections',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
