# Generated by Django 5.1.1 on 2024-10-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmodule', '0014_coupon_created_at_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractiveplan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
